ERROR 2017-10-23 06:52:40,598 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /check／
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 62, in process_request
    if self.should_redirect_with_slash(request):
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 80, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/Library/Python/2.7/site-packages/django/urls/base.py", line 158, in is_valid_path
    resolve(path, urlconf)
  File "/Library/Python/2.7/site-packages/django/urls/base.py", line 27, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:40,631 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /check／
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:40,667 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /check／
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,523 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,549 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,583 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,602 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,626 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,631 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /crowddata/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,646 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,649 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /crowddata/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,663 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,667 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /crowddata/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,683 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,690 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /crowddata/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,723 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /crowddata/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,763 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /crowddata/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,823 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /crowddata/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
ERROR 2017-10-23 06:52:47,869 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /crowddata/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 418, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lxbmain/PycharmProjects/neukgtm/neukgtm/urls.py", line 29, in <module>
    url(r'^bilingual/(?P<query>[^/]*)/(?P<page>[0-9]*)/$', views.bilingual, name="bilingual"),
AttributeError: 'module' object has no attribute 'bilingual'
INFO 2017-10-23 06:53:53,715 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：输入人员姓名或概念
WARNING 2017-10-23 06:54:16,033 /Library/Python/2.7/site-packages/django/core/handlers/base.py base.py base get_response 152: Not Found: /check／
INFO 2017-10-23 07:01:21,153 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：任飞亮
INFO 2017-10-23 07:01:21,800 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_researcher 61: 输入的参数：任飞亮
INFO 2017-10-23 07:01:34,916 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：任飞亮
INFO 2017-10-23 07:01:35,546 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_researcher 61: 输入的参数：任飞亮
INFO 2017-10-23 07:02:23,882 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：任飞亮
INFO 2017-10-23 07:02:23,882 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_researcher 61: 输入的参数：任飞亮
INFO 2017-10-23 07:02:40,986 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：输入人员姓名或概念
INFO 2017-10-23 07:02:51,719 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：任飞亮
INFO 2017-10-23 07:02:52,359 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_researcher 61: 输入的参数：任飞亮
INFO 2017-10-23 07:03:13,968 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：朱靖波
INFO 2017-10-23 07:03:14,683 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_researcher 61: 输入的参数：朱靖波
ERROR 2017-10-23 07:03:26,588 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /topic/语言学规则/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lxbmain/PycharmProjects/neukgtm/web/views.py", line 52, in topic
    topics = memcache.topic_generate(query)
  File "/Users/lxbmain/PycharmProjects/neukgtm/DataEngine/memcache.py", line 79, in topic_generate
    value = engine.get_info_topic(query)
  File "/Users/lxbmain/PycharmProjects/neukgtm/DataEngine/engine.py", line 173, in get_info_topic
    topic_data.bilingual_en.remove(topic_data.bilingual_en[topic_data.bilingual_cn.index(topic)])
IndexError: list index out of range
INFO 2017-10-23 07:05:04,756 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：朱靖波
INFO 2017-10-23 07:05:05,389 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_researcher 61: 输入的参数：朱靖波
INFO 2017-10-23 07:05:17,375 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_topic 74: 输入的参数：语言学规则
ERROR 2017-10-23 07:05:17,402 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /topic/语言学规则/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view web.views.topic didn't return an HttpResponse object. It returned None instead.
INFO 2017-10-23 07:07:53,348 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __new__ 27:  DBManager 实例 初始化
INFO 2017-10-23 07:07:53,348 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __init__ 41:  DBManager 连接池 pool 初始化
INFO 2017-10-23 07:07:53,361 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_keys like '%语言学规则%' or e_keys like '%语言学规则%' order by yea desc
INFO 2017-10-23 07:07:54,130 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：1
INFO 2017-10-23 07:07:54,131 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select ckey,ekey from bikey where ckey = '语言学规则' or ekey = '语言学规则'
INFO 2017-10-23 07:07:54,131 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：1
INFO 2017-10-23 07:07:54,132 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept2 = '语言学规则' order by confidence desc limit 0,10
INFO 2017-10-23 07:07:54,236 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 07:07:54,236 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept1 = '语言学规则' order by confidence desc limit 0,10
INFO 2017-10-23 07:07:54,333 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 07:07:54,334 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_topic 74: 输入的参数：语言学规则
ERROR 2017-10-23 07:07:54,360 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /topic/语言学规则/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view web.views.topic didn't return an HttpResponse object. It returned None instead.
INFO 2017-10-23 07:07:55,507 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __new__ 27:  DBManager 实例 初始化
INFO 2017-10-23 07:07:55,507 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __init__ 41:  DBManager 连接池 pool 初始化
INFO 2017-10-23 07:07:55,516 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_keys like '%语言学规则%' or e_keys like '%语言学规则%' order by yea desc
INFO 2017-10-23 07:07:56,307 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：1
INFO 2017-10-23 07:07:56,308 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select ckey,ekey from bikey where ckey = '语言学规则' or ekey = '语言学规则'
INFO 2017-10-23 07:07:56,308 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：1
INFO 2017-10-23 07:07:56,309 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept2 = '语言学规则' order by confidence desc limit 0,10
INFO 2017-10-23 07:07:56,412 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 07:07:56,413 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept1 = '语言学规则' order by confidence desc limit 0,10
INFO 2017-10-23 07:07:56,511 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 07:07:56,512 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_topic 74: 输入的参数：语言学规则
ERROR 2017-10-23 07:07:56,542 /Library/Python/2.7/site-packages/django/core/handlers/exception.py exception.py exception handle_uncaught_exception 135: Internal Server Error: /topic/语言学规则/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view web.views.topic didn't return an HttpResponse object. It returned None instead.
INFO 2017-10-23 07:09:13,541 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：朱靖波
INFO 2017-10-23 07:09:13,541 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __new__ 27:  DBManager 实例 初始化
INFO 2017-10-23 07:09:13,542 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __init__ 41:  DBManager 连接池 pool 初始化
INFO 2017-10-23 07:09:13,550 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_authors like '%朱靖波%' or e_authors like '%朱靖波%'
INFO 2017-10-23 07:09:14,159 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：20
INFO 2017-10-23 07:09:14,160 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_researcher 61: 输入的参数：朱靖波
INFO 2017-10-23 07:09:20,849 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __new__ 27:  DBManager 实例 初始化
INFO 2017-10-23 07:09:20,849 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __init__ 41:  DBManager 连接池 pool 初始化
INFO 2017-10-23 07:09:20,862 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_keys like '%语言学规则%' or e_keys like '%语言学规则%' order by yea desc
INFO 2017-10-23 07:09:21,837 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：1
INFO 2017-10-23 07:09:21,838 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select ckey,ekey from bikey where ckey = '语言学规则' or ekey = '语言学规则'
INFO 2017-10-23 07:09:21,839 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：1
INFO 2017-10-23 07:09:21,840 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept2 = '语言学规则' order by confidence desc limit 0,10
INFO 2017-10-23 07:09:21,976 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 07:09:21,976 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept1 = '语言学规则' order by confidence desc limit 0,10
INFO 2017-10-23 07:09:22,095 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 07:09:22,096 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_topic 74: 输入的参数：语言学规则
INFO 2017-10-23 07:09:45,537 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_keys like '%处理技术%' or e_keys like '%处理技术%' order by yea desc
INFO 2017-10-23 07:09:46,434 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：360
INFO 2017-10-23 07:09:46,436 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select ckey,ekey from bikey where ckey = '处理技术' or ekey = '处理技术'
INFO 2017-10-23 07:09:46,439 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：4
INFO 2017-10-23 07:09:46,440 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept2 = '处理技术' order by confidence desc limit 0,10
INFO 2017-10-23 07:09:46,553 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：10
INFO 2017-10-23 07:09:46,553 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept1 = '处理技术' order by confidence desc limit 0,10
INFO 2017-10-23 07:09:46,660 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：2
INFO 2017-10-23 07:09:46,661 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_topic 74: 输入的参数：处理技术
INFO 2017-10-23 07:10:02,472 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_keys like '%satellite communication signal%' or e_keys like '%satellite communication signal%' order by yea desc
INFO 2017-10-23 07:10:03,478 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：2
INFO 2017-10-23 07:10:03,479 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select ckey,ekey from bikey where ckey = 'satellite communication signal' or ekey = 'satellite communication signal'
INFO 2017-10-23 07:10:03,481 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：1
INFO 2017-10-23 07:10:03,482 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept2 = 'satellite communication signal' order by confidence desc limit 0,10
INFO 2017-10-23 07:10:03,601 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 07:10:03,601 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept1 = 'satellite communication signal' order by confidence desc limit 0,10
INFO 2017-10-23 07:10:03,706 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 07:10:03,707 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_topic 74: 输入的参数：satellite communication signal
INFO 2017-10-23 07:10:10,787 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：输入人员姓名或概念
INFO 2017-10-23 07:10:10,788 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_authors like '%输入人员姓名或概念%' or e_authors like '%输入人员姓名或概念%'
INFO 2017-10-23 07:10:11,442 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 07:10:11,442 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_keys like '%输入人员姓名或概念%' or e_keys like '%输入人员姓名或概念%' order by yea desc
INFO 2017-10-23 07:10:12,261 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 07:10:24,633 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database save 77: 存储sql：insert into uncheck(author, org, research, journal)values('dosa','sd','and','ads')
INFO 2017-10-23 07:10:36,157 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from uncheck
INFO 2017-10-23 07:10:36,157 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：2
INFO 2017-10-23 07:11:52,298 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __new__ 27:  DBManager 实例 初始化
INFO 2017-10-23 07:11:52,298 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __init__ 41:  DBManager 连接池 pool 初始化
INFO 2017-10-23 07:11:52,308 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from uncheck
INFO 2017-10-23 07:11:52,308 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：2
INFO 2017-10-23 10:55:17,662 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：任飞亮
INFO 2017-10-23 10:55:17,662 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __new__ 27:  DBManager 实例 初始化
INFO 2017-10-23 10:55:17,663 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __init__ 41:  DBManager 连接池 pool 初始化
INFO 2017-10-23 10:55:17,804 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_authors like '%任飞亮%' or e_authors like '%任飞亮%'
INFO 2017-10-23 10:55:20,343 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：2
INFO 2017-10-23 10:55:20,358 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_researcher 61: 输入的参数：任飞亮
INFO 2017-10-23 10:55:37,990 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_keys like '%多任务标注%' or e_keys like '%多任务标注%' order by yea desc
INFO 2017-10-23 10:55:38,960 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：1
INFO 2017-10-23 10:55:38,961 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select ckey,ekey from bikey where ckey = '多任务标注' or ekey = '多任务标注'
INFO 2017-10-23 10:55:38,969 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：1
INFO 2017-10-23 10:55:38,969 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept2 = '多任务标注' order by confidence desc limit 0,10
INFO 2017-10-23 10:55:39,108 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 10:55:39,108 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept1 = '多任务标注' order by confidence desc limit 0,10
INFO 2017-10-23 10:55:39,221 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 10:55:39,223 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_topic 74: 输入的参数：多任务标注
INFO 2017-10-23 10:55:47,475 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_keys like '%entity mention detection%' or e_keys like '%entity mention detection%' order by yea desc
INFO 2017-10-23 10:55:48,497 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：1
INFO 2017-10-23 10:55:48,498 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select ckey,ekey from bikey where ckey = 'entity mention detection' or ekey = 'entity mention detection'
INFO 2017-10-23 10:55:48,503 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 10:55:48,504 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept2 = 'entity mention detection' order by confidence desc limit 0,10
INFO 2017-10-23 10:55:48,632 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 10:55:48,633 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from OntologyFullRelation where concept1 = 'entity mention detection' order by confidence desc limit 0,10
INFO 2017-10-23 10:55:48,742 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 10:55:48,798 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views to_topic 74: 输入的参数：entity mention detection
INFO 2017-10-23 10:55:59,109 /Users/lxbmain/PycharmProjects/neukgtm/web/views.py views.py views search 22: 输入的参数：输入人员姓名或概念
INFO 2017-10-23 10:55:59,110 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_authors like '%输入人员姓名或概念%' or e_authors like '%输入人员姓名或概念%'
INFO 2017-10-23 10:55:59,782 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 10:55:59,783 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select distinct * from computer where c_keys like '%输入人员姓名或概念%' or e_keys like '%输入人员姓名或概念%' order by yea desc
INFO 2017-10-23 10:56:00,636 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：0
INFO 2017-10-23 10:56:38,504 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database save 77: 存储sql：insert into uncheck(author, org, research, journal)values('刘永康','东北大学','知识图谱','无')
INFO 2017-10-23 10:56:55,214 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from uncheck
INFO 2017-10-23 10:56:55,216 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：3
INFO 2017-10-23 10:57:45,435 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __new__ 27:  DBManager 实例 初始化
INFO 2017-10-23 10:57:45,435 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database __init__ 41:  DBManager 连接池 pool 初始化
INFO 2017-10-23 10:57:45,445 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 51: 查询的sql为：select * from uncheck
INFO 2017-10-23 10:57:45,446 /Users/lxbmain/PycharmProjects/neukgtm/DataEngine/database.py database.py database query 65: 查询结果数量为：3
